{
 "title": "Docker monitoring ARMB097",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ContainerName", "query": "label_values(container_name)" },
   {
    "name": "queryString",
    "query": "dataset-manager,studio-service,system-portal-svc,system-team-portal-svc,studio-runtime,studio-training,system-authz,manas-project,studio-model,dls-server,runtime-predictmanager,system-rcm,runtime-operationmanager,mls-taskmgr,job-compile,mls-livy,dls-jobscheduler,job-scheduler,mls-workflow-service,gateway"
   },
   { "name": "JobName", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"}[1m]) * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"} / container_spec_memory_limit_bytes{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"} * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Rss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"} / container_spec_memory_limit_bytes{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"} * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(container_memory_failures_total{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\",scope=\"container\",type=\"pgmajfault\"} [5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\",name=~\".*[[queryString]].*\",job=\"[[JobName]]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\",name=~\".*[[queryString]].*\",job=\"[[JobName]]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"}",
     "legendFormat": "memory_usage-{{container_name}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"}",
     "legendFormat": "memory-limit-{{container_name}}"
    },
    {
     "expr": "container_memory_rss{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"}",
     "legendFormat": "rss-{{container_name}}"
    },
    {
     "expr": "container_memory_cache{image!=\"\",container_name=~\"[[ContainerName]]\",job=\"[[JobName]]\"}",
     "legendFormat": "cache-{{container_name}}"
    }
   ]
  }
 ]
}